### PR TITLE
Teri art

### PR DESCRIPTION
**Pull request by Terieyenike**
# Issue number

https://github.com/dominicduffin1/python-turtle-art-canvas/issues/3

# Description

This PR shows a demonstration of creating circles and square with loops and included the art to the drawfunctions folder.

# Checklist

- [x] I have read and complied with the Code of Conduct and Content Guidelines as appropriate.
- [x] I have followed the Contributing Guide.
- [x] I agree to license my contribution under the License in this repository.
- [x] The program runs successfully after making my changes.

### CODE REVIEW

**Review by dominicduffin1 — CHANGES_REQUESTED** [review]
Thank you @Terieyenike! I like what you've done. Can you please move your work to a different part of the screen so the existing contributions are not covered by yours?

**Comment by Terieyenike** [comment]
I don't understand @dominicduffin1. Kindly explain.

Thanks.

**Comment by dominicduffin1** [comment]
Hi @Terieyenike!

See how on this screenshot your circle demo is being drawn on top of the star, tree and base at the center of the screen:

Screenshot (70)

If you could please move your circle demo to another part of the screen so they are still visible after it has been drawn, that would be great please!

**Comment by Terieyenike** [comment]
Thanks, @dominicduffin1. I will work on it.

**Comment by Terieyenike** [comment]
I have moved the art to a different location on the screen.

@dominicduffin1

**Review by dominicduffin1 — APPROVED** [review]
Perfect @Terieyenike! I love it!

**Pull request merged**
