### PR TITLE
Added David Akim art - Star

### PR DESCRIPTION
**Pull request by david-001**
# Issue number

#3

# Description

Added david_akim (drawing a star) to drawfunctions folder

# Checklist

- [x] I have read and complied with the Code of Conduct and Content Guidelines as appropriate.
- [x] I have followed the Contributing Guide.
- [x] I agree to license my contribution under the License in this repository.
- [x] The program runs successfully after making my changes.

### CODE REVIEW

**Review by dominicduffin1 — CHANGES_REQUESTED** [review]
Your contribution is great! Can you please restore the parts you deleted from `main.py` and shift the position of your star so it occupies its own space on the canvas.

**Comment by dominicduffin1** [comment]
Thank you @david-001 for your contribution! Once you resolve the issues from my review I'll merge it in! Also, sorry if this wasn't clear in the issue, I've updated it with another sentence to clarify it now.

**Comment by david-001** [comment]
Hi @dominicduffin1, I made the star smaller and placed it on top of your Christmas tree.

**Comment by dominicduffin1** [comment]
Amazing, thank you @david-001

**Review by dominicduffin1 — APPROVED** [review]

**Pull request merged**
